"""create listings and listing_images

Revision ID: 0841f353199c
Revises: 
Create Date: 2026-09-29 18:50:16.114148

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0841f353199c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('listings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('source_id', sa.String(length=32), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('price_pln', sa.Integer(), nullable=False),
    sa.Column('area_m2', sa.Numeric(precision=7, scale=2), nullable=False),
    sa.Column('price_per_m2', sa.Integer(), nullable=False),
    sa.Column('rooms', sa.SmallInteger(), nullable=True),
    sa.Column('floor', sa.SmallInteger(), nullable=True),
    sa.Column('build_year', sa.SmallInteger(), nullable=True),
    sa.Column('market', sa.String(length=16), nullable=True),
    sa.Column('seller_type', sa.String(length=16), nullable=True),
    sa.Column('building_type', sa.String(length=50), nullable=True),
    sa.Column('ownership', sa.String(length=80), nullable=True),
    sa.Column('city', sa.String(length=80), nullable=True),
    sa.Column('district', sa.String(length=80), nullable=True),
    sa.Column('district_source', sa.String(length=8), nullable=True),
    sa.Column('location_raw', sa.String(length=200), nullable=True),
    sa.Column('extra_attributes', sa.JSON(), nullable=False),
    sa.Column('flags', sa.JSON(), nullable=False),
    sa.Column('duplicate_of', sa.String(length=32), nullable=True),
    sa.Column('condition', sa.String(length=16), nullable=True),
    sa.Column('furnished', sa.String(length=8), nullable=True),
    sa.Column('balcony', sa.String(length=8), nullable=True),
    sa.Column('elevator', sa.String(length=8), nullable=True),
    sa.Column('parking', sa.String(length=12), nullable=True),
    sa.Column('monthly_fee_pln', sa.Integer(), nullable=True),
    sa.Column('ai_summary', sa.Text(), nullable=True),
    sa.Column('ai_enriched_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'source_id', name='uq_listings_source')
    )
    op.create_index(op.f('ix_listings_area_m2'), 'listings', ['area_m2'], unique=False)
    op.create_index(op.f('ix_listings_city'), 'listings', ['city'], unique=False)
    op.create_index(op.f('ix_listings_district'), 'listings', ['district'], unique=False)
    op.create_index(op.f('ix_listings_market'), 'listings', ['market'], unique=False)
    op.create_index(op.f('ix_listings_price_pln'), 'listings', ['price_pln'], unique=False)
    op.create_index(op.f('ix_listings_rooms'), 'listings', ['rooms'], unique=False)
    op.create_index('ix_listings_title_description_ft', 'listings', ['title', 'description'], unique=False, mysql_prefix='FULLTEXT')
    op.create_table('listing_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('listing_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('position', sa.SmallInteger(), nullable=False),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('listing_images')
    op.drop_index('ix_listings_title_description_ft', table_name='listings', mysql_prefix='FULLTEXT')
    op.drop_index(op.f('ix_listings_rooms'), table_name='listings')
    op.drop_index(op.f('ix_listings_price_pln'), table_name='listings')
    op.drop_index(op.f('ix_listings_market'), table_name='listings')
    op.drop_index(op.f('ix_listings_district'), table_name='listings')
    op.drop_index(op.f('ix_listings_city'), table_name='listings')
    op.drop_index(op.f('ix_listings_area_m2'), table_name='listings')
    op.drop_table('listings')
    # ### end Alembic commands ###
